shalalakpop: afplay ~/Music/Shalalakpop.aif
ship_bell: afplay ~/Music/Ship_Bell.mp3
initiating_shutdown_sequence: afplay ~/Music/initiating_shutdown_sequence.aif
chime_1: afplay ~/Music/chime_1.aif
chime_2: afplay ~/Music/chime_2.aif
chime_3: afplay ~/Music/chime_3.aif
chime_4: afplay ~/Music/chime_4.aif
chime_5: afplay ~/Music/chime_5.aif
chime_6: afplay ~/Music/chime_6.aif
chime_7: afplay ~/Music/chime_7.aif
chime_8: afplay ~/Music/chime_8.aif
chime_9: afplay ~/Music/chime_9.aif
chime_10: afplay ~/Music/chime_10.aif
chime_11: afplay ~/Music/chime_11.aif
chime_12: afplay ~/Music/chime_12.aif
deposit_confirmation: afplay ~/Music/deposit_confirmation.aif
mortgage_paid: afplay ~/Music/mortgage_paid.aif
blog_post_scott_res: afplay ~/Music/typewriter_one.aif
blog_post_realtor: afplay ~/Music/inyournewstoday.aif
