- alias: 'Shut off Entertainment Center Lights 2'
  trigger:
    platform: time
    minutes: '/1'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
        - condition: time
          after: '22:00:00'
        - condition: sun
          before: sunrise
      - condition: state
        entity_id: switch.entertainment_center
        state: 'on'
  action:
    - delay:
        milliseconds: 2690
    - service: switch.turn_off
      entity_id: switch.entertainment_center
