- alias: Jon Arrived at CrossFit Infinite Strength
  trigger:
    - platform: state
      entity_id: device_tracker.jons_iphone_7
      to: 'CrossFit Infinite Strength'
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'
  condition:
  action:
    - service: notify.ios_jons_iphone_7
      data:
        message: "Updated Spreadsheet"
    - service: ifttt.trigger
      data: {"event":"Crossfit_Infinite_Strength", "value1":"IN", "value2":"Jon"}



- alias: Jon Left CrossFit Infinite Strength
  trigger:
    - platform: state
      entity_id: device_tracker.jons_iphone_7
      from: 'CrossFit Infinite Strength'
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.good_night
      to: 'off'
      from: 'on'
  condition:
  action:
    service: ifttt.trigger
    data: {"event":"Crossfit_Infinite_Strength", "value1":"OUT", "value2":"Jon"}



- alias: Melanie Arrived at CrossFit Infinite Strength
  trigger:
    - platform: state
      entity_id: device_tracker.melanies_iphone_red
      to: 'CrossFit Infinite Strength'
    - platform: state
      entity_id: input_boolean.good_night
      to: 'on'
      from: 'off'
  condition:
  action:
    service: ifttt.trigger
    data: {"event":"Crossfit_Infinite_Strength", "value1":"IN", "value2":"Melanie"}



- alias: Melanie Left CrossFit Infinite Strength
  trigger:
    - platform: state
      entity_id: device_tracker.melanies_iphone_red
      to: 'CrossFit Infinite Strength'
    - platform: state
      entity_id: input_boolean.good_night
      to: 'off'
      from: 'on'
  condition:
  action:
    service: ifttt.trigger
    data: {"event":"Crossfit_Infinite_Strength", "value1":"OUT", "value2":"Melanie"}
